tpl:
  build: ./onbuild
dev:
  build: .
  ports:
    - "41439:3000"
    - "41438:22"
  volumes:
    - /var/lib/docker/vfs/dir/logcenter/update-dev.microservice.com:/data/log
    - /var/lib/docker/vfs/dir/datacenter/update-dev.microservice.com:/data/persist
    - /var/lib/docker/vfs/dir/filecenter/update-dev.microservice.com:/data/file
  environment:
    - EMAIL=jpchen@leadstec.com
    - ENGINE=localhost
    - ENABLE_SSHD=true
    - UPDATE_ENV=development
    - PORT=3000
    - UPDATE_DBNAME=updateservice
  links:
    - devdb:db
  hostname: update-dev.microservice.com
  restart: always
devdb:
  image: reg.leadstec.com/mongo:latest
  ports:
    - "41437:27017"
  volumes:
    - /var/lib/docker/vfs/dir/logcenter/update-dev-db.microservice.com:/data/log
    - /var/lib/docker/vfs/dir/dbcenter/update-dev-db.microservice.com:/data/db
    - /var/lib/docker/vfs/dir/datacenter/update-dev-db.microservice.com:/data/persist
  environment:
    - EMAIL=jpchen@leadstec.com
    - ENGINE=localhost
    - MONGO_TYPE=normal
    - MONGOD_ENABLE_SMALLFILES=true
  hostname: update-dev-db.microservice.com
  restart: always
