tpl:
  build: ./onbuild
dev:
  build: .
  ports:
    - "41436:3000"
    - "41435:22"
  volumes:
    - /var/lib/docker/vfs/dir/logcenter/notes-dev.microservices.com:/data/log
    - /var/lib/docker/vfs/dir/datacenter/notes-dev.microservices.com:/data/persist
  environment:
    - EMAIL=jpchen@leadstec.com
    - ENGINE=localhost
    - ENABLE_SSHD=true
    - NODE_ENV=development
    - PORT=3000
    - STACK_DBNAME=appstack
    - STACK_SESSION_SECRET=appstack
  links:
    - devdb:db
  hostname: notes-dev.microservices.com
devdb:
  image: reg.leadstec.com/mongo:latest
  ports:
    - "41434:27017"
  volumes:
    - /var/lib/docker/vfs/dir/logcenter/notes-dev.microservices.com:/data/log
    - /var/lib/docker/vfs/dir/dbcenter/notes-dev.microservices.com:/data/db
    - /var/lib/docker/vfs/dir/datacenter/notes-dev.microservices.com:/data/persist
  environment:
    - EMAIL=jpchen@leadstec.com
    - ENGINE=localhost
    - MONGO_TYPE=normal
  hostname: notes-dev-db.microservices.com
db:
  image: reg.leadstec.com/mongo:latest
  ports:
    - "41438:27017"
    - "41437:28017"
  volumes:
    - /var/lib/docker/vfs/dir/logcenter/notes-db.microservers.com:/data/log
    - /var/lib/docker/vfs/dir/dbcenter/notes-db.microservers.com:/data/db
    - /var/lib/docker/vfs/dir/datacenter/notes-db.microservers.com:/data/persist
  environment:
    - EMAIL=jpchen@leadstec.com
    - ENGINE=localhost
    - MONGO_TYPE=normal
    - MONGO_HTTP_INTERFACE=true
  hostname: note-db.microservers.com
noteMicroservers:
  image: {{BASE_IMAGE}}
  ports:
    - "41440:3000"
    - "41439:22"
  volumes:
    - /var/lib/docker/vfs/dir/logcenter/notes.microservers.com:/data/log
    - /var/lib/docker/vfs/dir/datacenter/notes.microservers.com:/data/persist
  links:
    - db:db
  environment:
    - EMAIL=jpchen@leadstec.com
    - ENGINE=vagrant
    - ENABLE_SSHD=true
  links:
    - db:db
  hostname: note.microservers.com
